server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.131.180.50:3306/yandatabase?serverTimezone=GMT%2b8
    username: YanPro
    password: 123456
  messages:
      # 国际化资源文件路径
      basename: i18n/messages
  profiles:
      active: druid
        # 文件上传
  servlet:
      multipart:
          # 单个文件大小
       max-file-size: 50MB
          # 设置总上传的文件大小
       max-request-size: 1024MB
  mail:
    protocol: smtp
        # 配置 SMTP 服务器地址
    host: smtp.qq.com
        # 发送者邮箱
    username: 1577889037@qq.com
        # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: tgklljuruvfdgbbg
      # 端口号465或587
        #    port: 465
    port: 587
        # 默认的邮件编码为UTF-8
    default-encoding: UTF-8

mybatis:
  mapper-locations: classpath:mapper/*.xml #扫描所有mybatis的xml配置文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
#    path: D:/代码/files/
    path: YanProFiles/

